Implement new Ops agent policy module
terraform-google-modules/terraform-google-cloud-operations pull request #101
Opened 2024-05-15 22:19 UTC by hsmatulisgoogle

2024-05-23 18:30 UTC, imrannayer commented
@hsmatulisgoogle can u plz follow [this doc](https://github.com/terraform-google-modules/terraform-google-cloud-operations/blob/master/CONTRIBUTING.md)

2024-05-31 14:57 UTC, hsmatulisgoogle commented
Fixed the lint issues and believe I followed the doc. Could you please allow the integration tests to run?

2024-06-04 19:02 UTC, g-awmalik commented
/gcbrun

2024-06-12 00:03 UTC, g-awmalik requested changes
LGTM for the most part. Please review the nits and a few comments. I'll approved after you resolve them.

2024-06-12 00:03 UTC, g-awmalik commented on modules/ops-agent-policy/main.tf
> +                dynamic "enforce" {
nit: whitespace

2024-06-12 00:03 UTC, g-awmalik commented on modules/ops-agent-policy/main.tf
> +
nit: whitespace

2024-06-21 08:19 UTC, hsmatulisgoogle commented on modules/ops-agent-policy/main.tf
> +        dynamic "inventory_filters" {
They cannot as the inventory_filters in resource_groups comes from a fixed template, and the inventory_filters outside block is user provided. The first one is meant to select the VMs that the policy applies to in general and the second one selects which steps to apply to which VM. Here is an example from the documentation https://registry.terraform.io/providers/hashicorp/google/latest/docs/resources/os_config_os_policy_assignment#example-usage---os-config-os-policy-assignment-basic

2024-06-21 08:30 UTC, hsmatulisgoogle commented on modules/ops-agent-policy/variables.tf
> +    exclusion_labels : optional(list(object({
They cannot. This excludes a VM if it contains all label-value pairs for some element in the list

2024-06-24 15:59 UTC, g-awmalik commented
/gcbrun

2024-06-24 17:57 UTC, g-awmalik approved these changes

2024-06-24 17:57 UTC, merged