Promote alpha to beta
terraform-google-modules/terraform-google-cloud-operations pull request #11
Opened 2021-02-01 20:12 UTC by sophieyfang

gcloud beta compute instances ops-agents policies command is publicly available now. Adjusting the alpha command to beta command.

https://cloud.google.com/sdk/gcloud/reference/beta/compute/instances/ops-agents/policies/

2021-02-01 20:19 UTC, bharathkkb requested changes
Thanks for the PR @sophieyfang 
You will need to bump the provider versions to `3.38`>= here: https://github.com/terraform-google-modules/terraform-google-cloud-operations/blob/c902fb091f13f05d9f14eb8c986e03ce481c7730/test/setup/versions.tf#L25

2021-02-01 20:49 UTC, sophieyfang commented
> Thanks for the PR @sophieyfang
> You will need to bump the provider versions to `3.38`>= here:
> 
> https://github.com/terraform-google-modules/terraform-google-cloud-operations/blob/c902fb091f13f05d9f14eb8c986e03ce481c7730/test/setup/versions.tf#L25

Somehow, it's still pulling a quite old cloud SDK: https://screenshot.googleplex.com/5azgYSqJTFNreGq

2021-02-01 21:38 UTC, bharathkkb commented
@sophieyfang if you want to specify a certain SDK you can pass that into the gcloud module [here](https://github.com/terraform-google-modules/terraform-google-cloud-operations/blob/c902fb091f13f05d9f14eb8c986e03ce481c7730/modules/agent-policy/main.tf#L17) via `gcloud_sdk_version`
Ref: https://github.com/terraform-google-modules/terraform-google-gcloud#inputs

2021-02-01 21:46 UTC, sophieyfang commented
> @sophieyfang if you want to specify a certain SDK you can pass that into the gcloud module [here](https://github.com/terraform-google-modules/terraform-google-cloud-operations/blob/c902fb091f13f05d9f14eb8c986e03ce481c7730/modules/agent-policy/main.tf#L17) via `gcloud_sdk_version`
> Ref: https://github.com/terraform-google-modules/terraform-google-gcloud#inputs

Thanks a lot! I just pinned it to `325.0.0`. Do you know why it's somehow '308.0.0' when it's not specified? I saw the default shall be `281.0.0`. Where does this `308.0.0` come from?

Another question for the `google-beta` which i specified to be >=3.54.0, i can see it pulls the latest 3.55.0 from today's release. Do you know what cloud-sdk that this `google-beta` map to? It seems they are not directly related?

2021-02-01 21:57 UTC, bharathkkb commented
> Where does this 308.0.0 come from?

Apologies, I just saw it had actually failed on verify step and not converge. For verify we use the gcloud in the container image, in this case the container image is pinned to 0.13.7 [here](https://github.com/terraform-google-modules/terraform-google-cloud-operations/blob/c902fb091f13f05d9f14eb8c986e03ce481c7730/build/int.cloudbuild.yaml#L48) which was build from this [commit](https://github.com/GoogleCloudPlatform/cloud-foundation-toolkit/pull/784/files) which has gcloud at 308. You could set it to `0.14` [which](https://github.com/GoogleCloudPlatform/cloud-foundation-toolkit/blob/4728355604fe7d9ec758e877f3f3e82a6ab7a23b/infra/build/Makefile#L17) will have Terraform 0.14.5 and gcloud 325.

> Another question for the google-beta which i specified to be >=3.54.0, i can see it pulls the latest 3.55.0 from today's release

This actually maps the Terraform provider binary and is not related to gcloud. The reason why it initially gave an error is because the project factory module used in the tests required a newer version of this due to upstream changes in that module.

2021-02-01 22:29 UTC, sophieyfang commented
> > Where does this 308.0.0 come from?
> 
> Apologies, I just saw it had actually failed on verify step and not converge. For verify we use the gcloud in the container image, in this case the container image is pinned to 0.13.7 [here](https://github.com/terraform-google-modules/terraform-google-cloud-operations/blob/c902fb091f13f05d9f14eb8c986e03ce481c7730/build/int.cloudbuild.yaml#L48) which was build from this [commit](https://github.com/GoogleCloudPlatform/cloud-foundation-toolkit/pull/784/files) which has gcloud at 308. You could set it to `0.14` [which](https://github.com/GoogleCloudPlatform/cloud-foundation-toolkit/blob/4728355604fe7d9ec758e877f3f3e82a6ab7a23b/infra/build/Makefile#L17) will have Terraform 0.14.5 and gcloud 325.
> 
> > Another question for the google-beta which i specified to be >=3.54.0, i can see it pulls the latest 3.55.0 from today's release
> 
> This actually maps the Terraform provider binary and is not related to gcloud. The reason why it initially gave an error is because the project factory module used in the tests required a newer version of this due to upstream changes in that module.

Thanks for the detailed explanation!!
I just updated the images to 0.14.9; Howeverr, it failed at this error:
```
Already have image (with digest): gcr.io/cloud-foundation-cicd/cft/developer-tools:0.14.9
Warning: The terraform state file at test/setup either has no outputs defined, or the terraform configuration has notbeen provisioned yet.
Error: SERVICE_ACCOUNT_JSON must contain the JSON string (not the
file path) of the service account credentials.  For example:
export SERVICE_ACCOUNT_JSON=$(< ~/.credentials/my-sa-key.json)
```

2021-02-02 02:27 UTC, bharathkkb commented
It should be safe to ignore the constraint warnings. Project-factory 10.0 dropped support for `skip_gcloud_download ` so we should remove that [here](https://github.com/terraform-google-modules/terraform-google-cloud-operations/blob/c902fb091f13f05d9f14eb8c986e03ce481c7730/test/setup/main.tf#L26). We also have some docs changes (due to upgrade to a newer version of terraform-docs which we use to autogenerate readmes), which you can fix by running `make generate_docs`

2021-02-02 05:02 UTC, bharathkkb commented
`terraform fmt -recursive` should fix the formatting issues

2021-02-03 19:25 UTC, sophieyfang commented
> `terraform fmt -recursive` should fix the formatting issues

Thanks a lot!!

2021-02-03 20:05 UTC, morgante approved these changes

2021-02-03 20:11 UTC, bharathkkb approved these changes
Thanks for working through this!

2021-02-03 20:11 UTC, merged

2021-02-03 20:12 UTC, sophieyfang commented
> Thanks for working through this!

Thanks for helping along! :)

2021-03-08 20:14 UTC, qingling128 commented
Hi, do we have any scheduled release(s) coming for this repo?

2021-03-08 20:30 UTC, bharathkkb commented
@qingling128 thanks for checking, just released `0.2.0`

2021-03-08 20:50 UTC, qingling128 commented
Thank you!